### ISSUE TITLE
Add an author field

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#468]
**Is your feature request related to a problem? Please describe.**
Add a field to each tome's metadata to credit the author.

**Describe the solution you'd like**
this will look like:
```yaml
author:
- name: Hulto
  github: https://github.com/hulto
```

This will also update the ents in the backend and rendered in the UI when a tomes view is created.

**Describe alternatives you've considered**
na 

**Additional context**
na
