### ISSUE TITLE
Toms params/result metadata

### ISSUE THREAD

**Issue by chutuananh2k** [spellshift/realm#742]
- Tome should define return type as well.
- Params/return metadata should provide a presentation field, borrow from html. For ex:
```
paramdefs:
    - name: path
      type: string
      view: input
      label: Absolute file path
      placeholder: "/etc/passwd"
```
```
resultdefs:
    - name: file
      type: binary
      view: img
      label: Screenshot
      placeholder:"spinner.png"
```

Or we can leverage protobuf to define params/result. It will make gui to generate form input and output much easier.
